name: Publish Blog Posts on Hashnode
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: prettyirrelevant/hashnode-posts-publisher@v0.1.1
        with:
          supported-formats: md
          posts-directory: hashnode-blogs
          access-token: ${{ secrets.HASHNODE_TOKEN }}
          publication-id: ${{ secrets.HASHNODE_PUBLICATION_ID }}
